// <auto-generated />
using System;
using FocusAssistant.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FocusAssistant.Data.Migrations
{
    [DbContext(typeof(FocusAssistantDbContext))]
    partial class FocusAssistantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FocusAssistant.Core.Models.AppUsage", b =>
                {
                    b.Property<int>("aID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProductive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("wID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("aID");

                    b.HasIndex("StartTime");

                    b.HasIndex("wID");

                    b.ToTable("AppUsages");
                });

            modelBuilder.Entity("FocusAssistant.Core.Models.UserSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DistractionEvents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FocusTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MostUsedAppsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductivityScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("StartTime");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("FocusAssistant.Core.Models.WorkSession", b =>
                {
                    b.Property<string>("wID")
                        .HasColumnType("TEXT");

                    b.Property<int>("AppSwitches")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("BreakTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DistractedTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ProductiveTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductivityScore")
                        .HasColumnType("REAL");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopAppsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("wID");

                    b.HasIndex("SessionId");

                    b.HasIndex("StartTime");

                    b.ToTable("WorkSessions");
                });

            modelBuilder.Entity("FocusAssistant.Core.Models.AppUsage", b =>
                {
                    b.HasOne("FocusAssistant.Core.Models.WorkSession", "WorkSession")
                        .WithMany("AppUsages")
                        .HasForeignKey("wID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkSession");
                });

            modelBuilder.Entity("FocusAssistant.Core.Models.WorkSession", b =>
                {
                    b.HasOne("FocusAssistant.Core.Models.UserSession", "UserSession")
                        .WithMany("WorkSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("FocusAssistant.Core.Models.UserSession", b =>
                {
                    b.Navigation("WorkSessions");
                });

            modelBuilder.Entity("FocusAssistant.Core.Models.WorkSession", b =>
                {
                    b.Navigation("AppUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
